package br.com.ucsal.util;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class DatabaseUtil {

    private static final String URL = "jdbc:hsqldb:mem:lojadb";
    private static final String USER = "sa";
    private static final String PASSWORD = "";
    
    public static void iniciarBanco() {
    	try {
    		Class.forName("org.hsqldb.jdbc.JDBCDriver");
    	}catch (ClassNotFoundException e){
    		e.printStackTrace();
    	}
    	
    	try (Connection conn = DriverManager.getConnection(URL, USER, PASSWORD);
    			Statement stmt = conn.createStatement()){
    		stmt.executeUpdate("CREATE TABLE IF NOT EXISTS produtos (" +
                    "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "nome VARCHAR(50), " +
                    "preco DOUBLE" +
                    ")");
    		
    		stmt.executeUpdate("INSERT INTO produtos (nome, preco) VALUES ('Notebook', 3500.00");
    		stmt.executeUpdate("INSERT INTO produtos (nome, preco) VALUES ('Smartphone', 1500.00");
    		stmt.executeUpdate("INSERT INTO produtos (nome, preco) VALUES ('Televisão 50 Polegadas', 2900.00");
    		stmt.executeUpdate("INSERT INTO produtos (nome, preco) VALUES ('Headset', 2700.00");
    		
    		System.out.println("O Banco de Dados foi Conectado/Iniciado com sucesso!");
    	}catch(Exception e) {
    		e.printStackTrace();
    	}
    }
    
    public static Connection getConnection() throws SQLException{
    	return DriverManager.getConnection(URL, USER, PASSWORD);
    }
}
